sudo: required
language: python
services:
- docker
before_install:
- docker -v
- docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
install: make build-all
script: make test-all
deploy:
- make tag-all
- make push-all
